[paths]
build = "_build"
merged = "_merged"
conflicts = "_conflicts"
tracking = "_tracking"
my_mod = "my_patch"

[templates]
replace = "{source_dir}/{source_name}_replace_{source_mod_id}.txt"
merge = "{source_dir}/����_all_merged_common_items_replace.txt"
snapshot = "{mod_name}_{source_name}.txt"
metadata_line = "# {key}: {value}"

[mods]
vanilla = "/disks/SteamLibrary/SteamLibrary/steamapps/common/Stellaris"
my_patch = "_My Patch"
pd_arcologies = "Imports/Planetary Diversity - More Arcologies"
bpvr_base = "Imports/BPVR - More Building Slots"
bpvr_compat = "Imports/BPVR - Compatibility Patch"

[[conflicts.rules]]
any_from = ["vanilla"]
with_any = ["my_patch"]

[[conflicts.rules]]
any_from = ["my_patch", "pd_arcologies"]
with_any = ["my_patch", "bpvr_base", "bpvr_compat"]

[priority]
bpvr_compat = 0
pd_arcologies = 1
vanilla = 2
bpvr_base = 3
my_patch = 4
